name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

defaults:
  run:
    working-directory: ./pyfru
    
jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: astral-sh/ruff-action@v3
      - run: ruff format --check
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v6
      - name: Build package
        uses: PyO3/maturin-action@v1
        with:
          args: --release --out dist
      - name: pytest
        run: |
          set -e
          pip install pyfru --find-links dist
          pip install pytest
          pytest
